### ISSUE TITLE
Rename or extend `autols-toggle` behaviour

### ISSUE THREAD

**Issue by jens-hj** [Kristoffer-PBS/autols-fish#2]
When invoking the `autols-toggle` command without any arguments one would expect it to switch to `on` if currently `off` or vice versa. However, currently it simply tells the user the state of `autols`.

Thus I would suggest either
1. Renaming the command such that the `toggle` semantics aren't in the command name. This could be something like `autols-set` and the invocation would then be `autols-set on/off` which seems rather intuitive, and doens't imply any toggling behaviour, which currently isn't present.
2. Or actually make it toggle the state as described above, and in this case maybe there should also be an `autols-state` command. The `autols-toggle` could still take an argument of `on/off` in this case if the user isn't currently aware of the state and simply want to force a specific one. As long as the toggling behaviour is also there if the name suggests that.

**Comment by kpbaks** [comment]
I have just spent some time rewriting the plugin, and add some new functionality. With the new `autols` function, it should now be more semantically clear how to interact with the plugin.
